import Foundation

let homeMokData = HomeDataModel(data: [HomeData(sectionTitle: "",
                                                data: [.init(image: ImageLiterals.video1,
                                                             title: "",
                                                             rank: nil,
                                                             maker: nil,
                                                             rating: nil),
                                                       .init(image: ImageLiterals.video2,
                                                             title: "",
                                                             rank: nil,
                                                             maker: nil,
                                                             rating: nil),
                                                       .init(image: ImageLiterals.video3,
                                                             title: "",
                                                             rank: nil,
                                                             maker: nil,
                                                             rating: nil),
                                                       .init(image: ImageLiterals.video4,
                                                             title: "",
                                                             rank: nil,
                                                             maker: nil,
                                                             rating: nil),
                                                       .init(image: ImageLiterals.video5,
                                                             title: "",
                                                             rank: nil,
                                                             maker: nil,
                                                             rating: nil)]),
                                       .init(sectionTitle: "티빙에서 꼭 봐야하는 콘텐츠",
                                             data: [.init(image: ImageLiterals.video2,
                                                          title: "시그널1",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video2,
                                                          title: "시그널2",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video3,
                                                          title: "시그널3",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video4,
                                                          title: "시그널4",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video5,
                                                          title: "시그널5",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil)]),
                                       .init(sectionTitle: "인기 LIVE 채널",
                                             data: [.init(image: ImageLiterals.video2,
                                                          title: "보이즈 플래닛 12화",
                                                          rank: 1,
                                                          maker: "Mnet",
                                                          rating: 80.0),
                                                    .init(image: ImageLiterals.video2,
                                                          title: "하트시그널",
                                                          rank: 2,
                                                          maker: "TVN",
                                                          rating: 75.1),
                                                    .init(image: ImageLiterals.video3,
                                                          title: "하트시그널2",
                                                          rank: 3,
                                                          maker: "TVN",
                                                          rating: 67.3),
                                                    .init(image: ImageLiterals.video4,
                                                          title: "프로듀스101",
                                                          rank: 4,
                                                          maker: "Mnet",
                                                          rating: 31.2),
                                                    .init(image: ImageLiterals.video5,
                                                          title: "프로듀스10001",
                                                          rank: 5,
                                                          maker: "KBS",
                                                          rating: 0.007)]),
                                       .init(sectionTitle: "1화 무료! 파라마운트+ 인기 시리즈",
                                             data: [.init(image: ImageLiterals.video2,
                                                          title: "시그널1",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video2,
                                                          title: "시그널2",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video3,
                                                          title: "시그널3",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video4,
                                                          title: "시그널4",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video5,
                                                          title: "시그널5",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil)]),
                                       .init(sectionTitle: "", data: [.init(image: ImageLiterals.banner,
                                                                            title: "",
                                                                            rank: nil,
                                                                            maker: nil,
                                                                            rating: nil)]),
                                       .init(sectionTitle: "마술보다 더 신비로운 영화(신비로운 영화사전님)",
                                             data: [.init(image: ImageLiterals.video2,
                                                          title: "시그널1",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video2,
                                                          title: "시그널2",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video3,
                                                          title: "시그널3",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video4,
                                                          title: "시그널4",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil),
                                                    .init(image: ImageLiterals.video5,
                                                          title: "시그널5",
                                                          rank: nil,
                                                          maker: nil,
                                                          rating: nil)])])


